### ISSUE TITLE
Recognize numeric data types

### ISSUE THREAD

**Issue by nineinchnick** [starburstdata/grafana-trino#14]
I tried running a query like this:
```sql
select date_trunc('day', created_at), count(*) as num_issues from hive.v2.issues group by 1 order by 1
```
and got:
```
Data is missing a number field
```
after checking the query inspector, it turned out that the count is recognized as a string, not an integer.

**Comment by mrveera** [comment]
String is default type when it is not able to find respective converter based on InputTypeName and ScanType is not provided.

What is column database type ?
we can just add converter based on that type and it should work

**Comment by nineinchnick** [comment]
Done in 18fb8d9199b6b2dcb62f2d060ef505d494074945
