### ISSUE TITLE
Getting unassigned external datasource | High Priority

### ISSUE THREAD

**Issue by nupurzs** [starburstdata/grafana-trino#145]
Trino folder is showing inside the /var/lib/grafana/plugin, while adding datasource getting 404 error.

**Below is my Dockerfile**
```
FROM grafana/grafana-oss:latest
COPY . /var/lib/grafana/plugins/trino
ENV GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=trino-datasource
EXPOSE 3000
VOLUME /var/lib/grafana/plugins/trino
```

I tried follwing the steps in https://github.com/grafana/loki/issues/6168 but not able to get the context of installing yarn.
Can you please help?
<img width="908" alt="image" src="https://user-images.githubusercontent.com/97525897/205627555-f9a4de96-55b7-4f69-b381-43bf1939cbf6.png">

**Comment by nineinchnick** [comment]
Are you running this in a local working copy of the repository or in a directory where you extracted the artifacts from the release? https://github.com/starburstdata/grafana-trino/releases/tag/v1.0.0-beta.2

**Comment by nupurzs** [comment]
@nineinchnick i tried accessing the zip but its showing me not found.
Can you please help me with the zip url?
Correct me if I am going wrong, **steps should be:**
****1)Download zip in local**
**2)Create Dockerfile and build image****
```
FROM grafana/grafana-oss:latest
COPY . /var/lib/grafana/plugins/trino
ENV GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=trino-datasource
EXPOSE 3000
VOLUME /var/lib/grafana/plugins/trino
```
**3)Use image**

Please let me know if i am missing anything.

Thanks & Regards
Nupur singh

**Comment by nineinchnick** [comment]
Which URL did you try? The one I added in my first comment, which you can find in the releases tab in this repo?

The steps look ok, just unzip the zipfile after downloading it.

**Comment by nineinchnick** [comment]
I'm closing this since it's not an actual issue with the connector but rather a question about usage.
