### ISSUE TITLE
Can not connect to data source

### ISSUE THREAD

**Issue by eronrunner** [starburstdata/grafana-trino#38]
After starting the Grafana with Grafana-trino plugins:
1. choose the Grafana plugins and click on Create data source Button
2. choose the Data Source tab and change HTTP address and port: http://trino.query.com:8080
3. Then save & test, but the test data  source failed and shows the message
4. After checking the URL to that the request fetched, the URL is always localhost:3000/api/ds/query instead of the URL http://trino.query.com:8080
I also create a dashboard with a panel using trino-datasource, and the query isalways failed and URL is localhost:3000/api/ds/query

I don't understand why but, please help me to check this. Appreciate it!

**Comment by nineinchnick** [comment]
If the `save & test` button fails, you can go into the `explore` and it should show a more detailed error message there. Also, try checking Grafana logs for errors. You might have to set the `GF_LOG_LEVEL=debug` environmental variable in the Grafana server to get more details from data source plugins.

**Comment by eronrunner** [comment]
Some images, hope these help to tracking the issue
Grafana gui
![image](https://user-images.githubusercontent.com/35225206/169788236-6a838389-ec60-4b07-b861-6306d1d7df0a.png)
The request:
![image](https://user-images.githubusercontent.com/35225206/169792991-d2aa931e-872b-43ad-9ec2-86d126922904.png)

Grafana logs
![image](https://user-images.githubusercontent.com/35225206/169791440-ea11fd4d-b593-4956-aa70-a976e6067576.png)

**Comment by nineinchnick** [comment]
The logs include a "plugin unavailable" error - this indicates the plugin process might have panicked. You really need to enable debug logs to see the panic stack trace from the plugin.

Which version of this plugin are you using? If you checked out the repository, which commit? Have you built everything, including running the `mage` command?

**Comment by nineinchnick** [comment]
I just noticed I haven't included the proper ZIP in the beta.1 release, so if you've used these artifacts get this one instead: https://github.com/starburstdata/grafana-trino/releases/download/v1.0.0-beta.1/trino-datasource.zip

**Comment by zjeoff** [comment]
![image](https://user-images.githubusercontent.com/25643034/169825879-3de8a0a8-c260-489e-a27c-500eac216a8e.png)

hi, nineinchnick, 
when i use this new plugin as your post here (https://github.com/starburstdata/grafana-trino/releases/download/v1.0.0-beta.1/trino-datasource.zip), i got a error when a a trino-datasource.

the error is : "this.getRef is not a function"

see the error picture as i attached.

Look forward to your help...

**Comment by nineinchnick** [comment]
@zjeoff can you create a separate issue for this? Please specify which Grafana version you're using.

**Comment by zjeoff** [comment]
@nineinchnick  sure , issue #39 has been submitted...

**Comment by eronrunner** [comment]
> The logs include a "plugin unavailable" error - this indicates the plugin process might have panicked. You really need to enable debug logs to see the panic stack trace from the plugin.
> 
> Which version of this plugin are you using? If you checked out the repository, which commit? Have you built everything, including running the `mage` command?

Oh,
I check logs when building lib by `mage `command, it might have somethings wrongs with `go `version. So I re-build and then restart grafana container, and it's working.

Thank you, @nineinchnick!
