### ISSUE TITLE
no datasource show up

### ISSUE THREAD

**Issue by zjeoff** [starburstdata/grafana-trino#45]
hi, Team

i can successfully add the trino-datasource after upgrade grafana to v8.5.. see below screenshot.

![image](https://user-images.githubusercontent.com/25643034/170304483-baca7308-5dc0-4459-9e44-efc4aacf550e.png)

however, it seems like i can not find/see  this trino data resource when i  tried to build a panel 
![image](https://user-images.githubusercontent.com/25643034/170304937-bda93067-b50a-46b9-8300-43d856abfd5e.png)

any idea?  not sure if i miss any steps?

**Comment by nineinchnick** [comment]
I'm having the same issue on my grafana instance, but I can't repro it locally.

**Comment by zjeoff** [comment]
@nineinchnick so what i can do?

**Comment by nineinchnick** [comment]
Not yet, I'll try to ask the Grafana community for help: https://community.grafana.com/t/custom-backend-data-source-not-showing-up-in-the-dropdown/66489

**Comment by zimmaz** [comment]
Hi guys, I'm having the same issue, the plugin is installed and successfully connected but it doesn't show in the dropdown menu when creating a graph. I set it as the default data source and it shows up when I want to edit the panel but once I change to another source it disappears.

any update?

**Comment by nineinchnick** [comment]
No update, you might want to comment on that Grafana community forum thread I linked above.

**Comment by nineinchnick** [comment]
This should be fixed now. I uploaded another pre-release zip.
